"""initial_schema

Revision ID: 8eebae4cd92e
Revises: 
Create Date: 2026-09-14 01:21:13.944694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eebae4cd92e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('authority_level', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('monthly_token_budget', sa.Integer(), nullable=False),
    sa.Column('tokens_used_this_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('authority_level', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_canonical_url'), 'knowledge_documents', ['canonical_url'], unique=True)
    op.create_index(op.f('ix_knowledge_documents_source_id'), 'knowledge_documents', ['source_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_credentials_organization_id'), 'oauth_credentials', ['organization_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('normalized_domain', sa.String(length=255), nullable=False),
    sa.Column('primary_url', sa.Text(), nullable=False),
    sa.Column('preferred_protocol', sa.String(length=10), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('cms_type', sa.String(length=50), nullable=True),
    sa.Column('execution_mode', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_normalized_domain'), 'sites', ['normalized_domain'], unique=False)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('state_before', sa.Text(), nullable=True),
    sa.Column('state_after', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_site_id'), 'audit_logs', ['site_id'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('crawl_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_urls_discovered', sa.Integer(), nullable=False),
    sa.Column('total_urls_crawled', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_site_id'), 'crawl_runs', ['site_id'], unique=False)
    op.create_table('crux_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('form_factor', sa.String(length=20), nullable=True),
    sa.Column('p75_lcp_ms', sa.Integer(), nullable=True),
    sa.Column('p75_inp_ms', sa.Integer(), nullable=True),
    sa.Column('p75_cls', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crux_metrics_site_id'), 'crux_metrics', ['site_id'], unique=False)
    op.create_table('gsc_search_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('page', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('device', sa.String(length=20), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('position', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsc_search_metrics_metric_date'), 'gsc_search_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_gsc_search_metrics_page'), 'gsc_search_metrics', ['page'], unique=False)
    op.create_index(op.f('ix_gsc_search_metrics_query'), 'gsc_search_metrics', ['query'], unique=False)
    op.create_index(op.f('ix_gsc_search_metrics_site_id'), 'gsc_search_metrics', ['site_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('document_title', sa.String(length=255), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('authority_level', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_claims', sa.Text(), nullable=False),
    sa.Column('verification_confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('lighthouse_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('score_performance', sa.Integer(), nullable=False),
    sa.Column('score_accessibility', sa.Integer(), nullable=False),
    sa.Column('score_best_practices', sa.Integer(), nullable=False),
    sa.Column('score_seo', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lighthouse_runs_site_id'), 'lighthouse_runs', ['site_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('rag_sources_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_priority_score'), 'recommendations', ['priority_score'], unique=False)
    op.create_index(op.f('ix_recommendations_site_id'), 'recommendations', ['site_id'], unique=False)
    op.create_table('site_connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_connectors_site_id'), 'site_connectors', ['site_id'], unique=False)
    op.create_table('site_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_verifications_site_id'), 'site_verifications', ['site_id'], unique=False)
    op.create_table('change_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_sets_site_id'), 'change_sets', ['site_id'], unique=False)
    op.create_table('crawl_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crawl_run_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_fetchable', sa.Boolean(), nullable=False),
    sa.Column('is_crawlable_by_google', sa.Boolean(), nullable=False),
    sa.Column('has_noindex', sa.Boolean(), nullable=False),
    sa.Column('is_indexable_candidate', sa.Boolean(), nullable=False),
    sa.Column('canonical_target', sa.Text(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=True),
    sa.Column('in_sitemap', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('raw_html_hash', sa.String(length=64), nullable=True),
    sa.Column('main_content_hash', sa.String(length=64), nullable=True),
    sa.Column('canonical_seo_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_pages_crawl_run_id'), 'crawl_pages', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_normalized_url'), 'crawl_pages', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_crawl_pages_site_id'), 'crawl_pages', ['site_id'], unique=False)
    op.create_table('change_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_set_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('state_before', sa.Text(), nullable=False),
    sa.Column('state_after', sa.Text(), nullable=False),
    sa.Column('expected_hash_before', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['change_set_id'], ['change_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_items_change_set_id'), 'change_items', ['change_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_items_change_set_id'), table_name='change_items')
    op.drop_table('change_items')
    op.drop_index(op.f('ix_crawl_pages_site_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_normalized_url'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_crawl_run_id'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    op.drop_index(op.f('ix_change_sets_site_id'), table_name='change_sets')
    op.drop_table('change_sets')
    op.drop_index(op.f('ix_site_verifications_site_id'), table_name='site_verifications')
    op.drop_table('site_verifications')
    op.drop_index(op.f('ix_site_connectors_site_id'), table_name='site_connectors')
    op.drop_table('site_connectors')
    op.drop_index(op.f('ix_recommendations_site_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority_score'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_lighthouse_runs_site_id'), table_name='lighthouse_runs')
    op.drop_table('lighthouse_runs')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_gsc_search_metrics_site_id'), table_name='gsc_search_metrics')
    op.drop_index(op.f('ix_gsc_search_metrics_query'), table_name='gsc_search_metrics')
    op.drop_index(op.f('ix_gsc_search_metrics_page'), table_name='gsc_search_metrics')
    op.drop_index(op.f('ix_gsc_search_metrics_metric_date'), table_name='gsc_search_metrics')
    op.drop_table('gsc_search_metrics')
    op.drop_index(op.f('ix_crux_metrics_site_id'), table_name='crux_metrics')
    op.drop_table('crux_metrics')
    op.drop_index(op.f('ix_crawl_runs_site_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_audit_logs_site_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_normalized_domain'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_oauth_credentials_organization_id'), table_name='oauth_credentials')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_knowledge_documents_source_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_canonical_url'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
